---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.common.namespace }}
data:
  {{- range $k, $v := .Values.config.envVars }}
  {{ $k }}: {{ $v | quote }}
  {{- end}}
