---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.common.namespace }}
  labels:
    app: {{ .Values.common.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.common.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.common.name }}
    spec:
      containers:
        - name: {{ .Values.common.name }}
          image: {{ .Values.deployment.image }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.common.name }}
            - secretRef:
                name: {{ .Values.common.name }}
