---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.common.namespace }}
data:
  {{- range $k, $v := .Values.secret.envVars }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end}}
