#
# Chart release
#

name: Chart release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      - name: Release chart
        uses: stefanprodan/helm-gh-pages@v1.5.0
        with:
          branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
