#
# Chart release
#

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Helm client
        uses: azure/setup-helm@v3.3
        with:
          version: v3.4.0
      - name: Release chart
        uses: helm/chart-releaser-action@v1.4.0
        with:
          branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
